In [66]:
import pandas as pd
# Read the CSV file into a DataFrame
df = pd.read_csv('csv_files/cleaned_dataset.csv')
df.head()
print(df.head())

             Locality  Zip Code  Type of Property Subtype of Property  \
0             Zelzate    9060.0               1.0               house
1  Monceau-sur-sambre    6031.0               1.0               house
2       S-gravenwezel    2970.0               1.0               villa
3         Sivry-rance    6470.0               1.0             mansion
4               Yvoir    5530.0               1.0               villa

       Price  Number of Rooms  Livable Space (m2)  Fully Equipped Kitchen  \
0   275000.0              3.0               149.0                     0.0
1   225000.0              2.0               179.0                     1.0
2  1949000.0              6.0               616.0                     1.0
3   319000.0              5.0               325.0                     1.0
4   235000.0              3.0               200.0                     0.0

   Furnished  Open Fire  Terrace  Terrace Area (m2)  Garden  Swimming Pool  \
0        0.0        0.0      0.0                0.0     0.0            0.0
1        0.0        0.0      1.0               12.0     0.0            0.0
2        0.0        1.0      0.0                0.0     0.0            0.0
3        0.0        1.0      1.0               40.0     1.0            0.0
4        0.0        0.0      1.0               52.0     0.0            0.0

   Surface of the Land (m2)  PEB  Primary Energy Consumption (kWh/m2)  \
0                     138.0  5.0                                190.0
1                     135.0  3.0                                328.0
2                   14581.0  5.0                                197.0
3                    1995.0  2.0                                408.0
4                     732.0  0.0                                566.0

   State of the Building                                                Url
0                    3.0  https://www.immoweb.be/en/classified/house/for...
1                    4.0  https://www.immoweb.be/en/classified/house/for...
2                    5.0  https://www.immoweb.be/en/classified/villa/for...
3                    3.0  https://www.immoweb.be/en/classified/mansion/f...
4                    1.0  https://www.immoweb.be/en/classified/villa/for...

In [67]:
print("Shape of df", df.shape)

Shape of df (16460, 19)

In [68]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16460 entries, 0 to 16459
Data columns (total 19 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Locality                             8722 non-null   object
 1   Zip Code                             8722 non-null   float64
 2   Type of Property                     8722 non-null   float64
 3   Subtype of Property                  8722 non-null   object
 4   Price                                8722 non-null   float64
 5   Number of Rooms                      8722 non-null   float64
 6   Livable Space (m2)                   8722 non-null   float64
 7   Fully Equipped Kitchen               8722 non-null   float64
 8   Furnished                            8722 non-null   float64
 9   Open Fire                            8722 non-null   float64
 10  Terrace                              8722 non-null   float64
 11  Terrace Area (m2)                    8722 non-null   float64
 12  Garden                               8722 non-null   float64
 13  Swimming Pool                        8722 non-null   float64
 14  Surface of the Land (m2)             8722 non-null   float64
 15  PEB                                  8722 non-null   float64
 16  Primary Energy Consumption (kWh/m2)  8722 non-null   float64
 17  State of the Building                8722 non-null   float64
 18  Url                                  8722 non-null   object
dtypes: float64(16), object(3)
memory usage: 2.4+ MB
None

In [69]:
df.dropna(subset=['Price'], inplace=True, ignore_index=True)
df.info(25)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8722 entries, 0 to 8721
Data columns (total 19 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Locality                             8722 non-null   object
 1   Zip Code                             8722 non-null   float64
 2   Type of Property                     8722 non-null   float64
 3   Subtype of Property                  8722 non-null   object
 4   Price                                8722 non-null   float64
 5   Number of Rooms                      8722 non-null   float64
 6   Livable Space (m2)                   8722 non-null   float64
 7   Fully Equipped Kitchen               8722 non-null   float64
 8   Furnished                            8722 non-null   float64
 9   Open Fire                            8722 non-null   float64
 10  Terrace                              8722 non-null   float64
 11  Terrace Area (m2)                    8722 non-null   float64
 12  Garden                               8722 non-null   float64
 13  Swimming Pool                        8722 non-null   float64
 14  Surface of the Land (m2)             8722 non-null   float64
 15  PEB                                  8722 non-null   float64
 16  Primary Energy Consumption (kWh/m2)  8722 non-null   float64
 17  State of the Building                8722 non-null   float64
 18  Url                                  8722 non-null   object
dtypes: float64(16), object(3)
memory usage: 1.3+ MB

In [70]:
df.head(20)

,Locality,Zip Code,Type of Property,Subtype of Property,Price,Number of Rooms,Livable Space (m2),Fully Equipped Kitchen,Furnished,Open Fire,Terrace,Terrace Area (m2),Garden,Swimming Pool,Surface of the Land (m2),PEB,Primary Energy Consumption (kWh/m2),State of the Building,Url
0,Zelzate,9060.0,1.0,house,275000.0,3.0,149.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,138.0,5.0,190.0,3.0,https://www.immoweb.be/en/classified/house/for...
1,Monceau-sur-sambre,6031.0,1.0,house,225000.0,2.0,179.0,1.0,0.0,0.0,1.0,12.0,0.0,0.0,135.0,3.0,328.0,4.0,https://www.immoweb.be/en/classified/house/for...
2,S-gravenwezel,2970.0,1.0,villa,1949000.0,6.0,616.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,14581.0,5.0,197.0,5.0,https://www.immoweb.be/en/classified/villa/for...
3,Sivry-rance,6470.0,1.0,mansion,319000.0,5.0,325.0,1.0,0.0,1.0,1.0,40.0,1.0,0.0,1995.0,2.0,408.0,3.0,https://www.immoweb.be/en/classified/mansion/f...
4,Yvoir,5530.0,1.0,villa,235000.0,3.0,200.0,0.0,0.0,0.0,1.0,52.0,0.0,0.0,732.0,0.0,566.0,1.0,https://www.immoweb.be/en/classified/villa/for...
5,Lokeren,9160.0,1.0,apartment-block,519000.0,5.0,550.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,349.0,2.0,496.0,3.0,https://www.immoweb.be/en/classified/apartment...
6,Gent,9031.0,1.0,house,279000.0,3.0,150.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,221.0,2.0,491.0,3.0,https://www.immoweb.be/en/classified/house/for...
7,Vosselaar,2350.0,1.0,manor-house,585000.0,4.0,459.0,1.0,0.0,1.0,1.0,30.0,1.0,1.0,2087.0,3.0,398.0,3.0,https://www.immoweb.be/en/classified/manor-hou...
8,Pollare,9401.0,1.0,house,258000.0,3.0,137.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,765.0,1.0,618.0,1.0,https://www.immoweb.be/en/classified/house/for...
9,Chimay,6460.0,1.0,house,225000.0,5.0,162.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,660.0,3.0,307.0,3.0,https://www.immoweb.be/en/classified/house/for...
10,Gent,9000.0,1.0,house,298000.0,2.0,94.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,57.0,5.0,117.0,5.0,https://www.immoweb.be/en/classified/house/for...
11,Erpent,5101.0,1.0,house,250000.0,3.0,183.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,680.0,3.0,304.0,1.0,https://www.immoweb.be/en/classified/house/for...
12,Bievre,5555.0,1.0,house,130000.0,7.0,270.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,622.0,0.0,576.0,1.0,https://www.immoweb.be/en/classified/house/for...
13,Aalst,9300.0,1.0,mansion,329000.0,4.0,222.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,160.0,2.0,416.0,3.0,https://www.immoweb.be/en/classified/mansion/f...
14,Langemark-poelkapelle,8920.0,1.0,house,319000.0,6.0,298.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,221.0,3.0,376.0,3.0,https://www.immoweb.be/en/classified/house/for...
15,Overijse,3090.0,1.0,house,348000.0,3.0,118.0,1.0,0.0,0.0,1.0,15.0,1.0,0.0,298.0,2.0,429.0,2.0,https://www.immoweb.be/en/classified/house/for...
16,Merendree,9850.0,1.0,house,325000.0,5.0,251.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,768.0,2.0,448.0,1.0,https://www.immoweb.be/en/classified/house/for...
17,Wetteren,9230.0,1.0,house,295000.0,3.0,151.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,578.0,2.0,429.0,1.0,https://www.immoweb.be/en/classified/house/for...
18,Wanze,4520.0,0.0,apartment,324000.0,8.0,358.0,0.0,0.0,0.0,1.0,28.0,1.0,0.0,0.0,4.0,189.0,3.0,https://www.immoweb.be/en/classified/apartment...
19,Opwijk,1745.0,1.0,house,319000.0,2.0,159.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,350.0,2.0,444.0,3.0,https://www.immoweb.be/en/classified/house/for...

In [71]:
df.describe()

,Zip Code,Type of Property,Price,Number of Rooms,Livable Space (m2),Fully Equipped Kitchen,Furnished,Open Fire,Terrace,Terrace Area (m2),Garden,Swimming Pool,Surface of the Land (m2),PEB,Primary Energy Consumption (kWh/m2),State of the Building
count,8722.000000,8722.000000,8.722000e+03,8722.000000,8722.000000,8722.000000,8722.000000,8722.000000,8722.00000,8722.000000,8722.000000,8722.000000,8722.000000,8722.000000,8722.000000,8722.000000
mean,5222.124857,0.719216,1.385304e+06,3.382366,208.354506,0.563747,0.027975,0.066842,0.37778,11.390163,0.295345,0.045402,1061.224031,3.353589,462.047008,3.101124
std,3116.144054,0.449408,2.250209e+07,1.769734,144.107912,0.495948,0.164911,0.249763,0.48486,37.742371,0.456224,0.208197,5340.680215,1.694455,3250.852694,1.282788
min,1000.000000,0.000000,4.500000e+04,1.000000,30.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,2250.000000,0.000000,2.490000e+05,2.000000,111.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,2.000000,166.000000,2.000000
50%,4500.000000,1.000000,3.650000e+05,3.000000,168.000000,1.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,255.000000,4.000000,258.000000,3.000000
75%,8500.000000,1.000000,5.790000e+05,4.000000,251.000000,1.000000,0.000000,0.000000,1.00000,12.000000,1.000000,0.000000,824.500000,5.000000,394.000000,4.000000
max,9992.000000,1.000000,1.000002e+09,47.000000,1100.000000,1.000000,1.000000,1.000000,1.00000,1834.000000,1.000000,1.000000,366356.000000,6.000000,122188.000000,5.000000

In [72]:
df.groupby('Zip Code')['Price'].describe()

,count,mean,std,min,25%,50%,75%,max
Zip Code,,,,,,,,
1000.0,107.0,6.196402e+05,454471.249866,179000.0,352500.0,460000.0,697000.0,2560000.0
1020.0,27.0,4.500741e+05,228409.033555,149000.0,287000.0,395000.0,585000.0,990000.0
1030.0,72.0,4.995208e+05,276927.018370,142500.0,292500.0,422500.0,656250.0,1490000.0
1040.0,38.0,8.157368e+05,625773.712844,189000.0,333000.0,540000.0,1268750.0,3100000.0
1050.0,97.0,8.306031e+05,610583.907429,159000.0,365000.0,550000.0,1050000.0,2590000.0
...,...,...,...,...,...,...,...,...
9981.0,1.0,4.470000e+05,NaN,447000.0,447000.0,447000.0,447000.0,447000.0
9982.0,1.0,5.500000e+05,NaN,550000.0,550000.0,550000.0,550000.0,550000.0
9990.0,12.0,5.963750e+05,300340.952086,247000.0,368500.0,548000.0,760500.0,1245000.0
9991.0,6.0,4.345000e+05,173062.705399,180000.0,350000.0,437500.0,523500.0,679000.0
9992.0,2.0,1.499500e+06,919945.922324,849000.0,1174250.0,1499500.0,1824750.0,2150000.0

In [73]:
#Count the number of unique values, two ways are possible
df['Locality'].value_counts().count()
df['Locality'].nunique()

1515

In [74]:
df['Zip Code'].value_counts().count()
df['Zip Code'].nunique()

881

In [75]:
#Count duplicates for the same properties that have different URL.
df.duplicated(subset=df.columns.difference(['Url'])).value_counts()

False    8722
Name: count, dtype: int64

In [76]:
#Remove duplicates for the same properties that have different URL.
df.drop_duplicates(subset=df.columns.difference(['Url']), inplace=True)

In [77]:
df.shape

(8722, 19)

In [78]:
# Create the new 'Open Fire' column based on 'Number of Fireplaces (0 for 0 fireplaces and 1 for more than 1 fireplaces)
df['Open Fire'] = df['Number of Fireplaces'].apply(lambda x: 0 if x == 0 else 1)

KeyError: 'Number of Fireplaces'

In [ ]:
df.shape

(9988, 24)

In [ ]:
df.head()

,Locality,Zip Code,Type of Property,Subtype of Property,Price,Type of Sale,Number of Rooms,Livable Space (m2),Fully Equipped Kitchen,Furnished,...,Garden Area (m2),Swimming Pool,Surface of the Land (m2),Number of Facades,Construction Year,PEB,Primary Energy Consumption (kWh/m2),State of the Building,Url,Open Fire
0,Ottignies-louvain-la-neuve,1348,House,exceptional-property,3790000,for-sale,6,750,0,0,...,0,1,160737,4,1961,E,359,To be done up,https://www.immoweb.be/en/classified/exception...,0
1,Anthee,5520,House,castle,550000,for-sale,2,200,1,0,...,0,0,110000,0,0,C,234,Good,https://www.immoweb.be/en/classified/castle/fo...,1
2,Dinant,5500,House,castle,550000,for-sale,2,200,1,0,...,0,0,110000,0,0,C,234,Good,https://www.immoweb.be/en/classified/castle/fo...,1
3,Namur,5000,House,castle,550000,for-sale,2,200,1,0,...,0,0,110000,0,0,C,234,Good,https://www.immoweb.be/en/classified/castle/fo...,1
4,Waasmunster,9250,House,castle,3000000,for-sale,6,967,0,0,...,0,1,101349,4,1810,F,708,Good,https://www.immoweb.be/en/classified/castle/fo...,1

In [ ]:
# Find the index of the current 'Number of Fireplaces' column
fireplaces_index = df.columns.get_loc('Number of Fireplaces')

In [ ]:
#Insert the new 'Open Fire' column at the same index
df.insert(fireplaces_index, 'Open Fire', df.pop('Open Fire'))

In [ ]:
df.shape

(9988, 24)

In [ ]:
df.head()

,Locality,Zip Code,Type of Property,Subtype of Property,Price,Type of Sale,Number of Rooms,Livable Space (m2),Fully Equipped Kitchen,Furnished,...,Garden,Garden Area (m2),Swimming Pool,Surface of the Land (m2),Number of Facades,Construction Year,PEB,Primary Energy Consumption (kWh/m2),State of the Building,Url
0,Ottignies-louvain-la-neuve,1348,House,exceptional-property,3790000,for-sale,6,750,0,0,...,0,0,1,160737,4,1961,E,359,To be done up,https://www.immoweb.be/en/classified/exception...
1,Anthee,5520,House,castle,550000,for-sale,2,200,1,0,...,0,0,0,110000,0,0,C,234,Good,https://www.immoweb.be/en/classified/castle/fo...
2,Dinant,5500,House,castle,550000,for-sale,2,200,1,0,...,0,0,0,110000,0,0,C,234,Good,https://www.immoweb.be/en/classified/castle/fo...
3,Namur,5000,House,castle,550000,for-sale,2,200,1,0,...,0,0,0,110000,0,0,C,234,Good,https://www.immoweb.be/en/classified/castle/fo...
4,Waasmunster,9250,House,castle,3000000,for-sale,6,967,0,0,...,0,0,1,101349,4,1810,F,708,Good,https://www.immoweb.be/en/classified/castle/fo...

In [ ]:
df.columns

Index(['Locality', 'Zip Code', 'Type of Property', 'Subtype of Property',
       'Price', 'Type of Sale', 'Number of Rooms', 'Livable Space (m2)',
       'Fully Equipped Kitchen', 'Furnished', 'Open Fire',
       'Number of Fireplaces', 'Terrace', 'Terrace Area (m2)', 'Garden',
       'Garden Area (m2)', 'Swimming Pool', 'Surface of the Land (m2)',
       'Number of Facades', 'Construction Year', 'PEB',
       'Primary Energy Consumption (kWh/m2)', 'State of the Building', 'Url'],
      dtype='object')

In [ ]:
#Rename a name of column "Open Fire" for "Number of Fireplaces"
df.rename(columns={'Open Fire': 'Number of Fireplaces'})

,Locality,Zip Code,Type of Property,Subtype of Property,Price,Type of Sale,Number of Rooms,Livable Space (m2),Fully Equipped Kitchen,Furnished,...,Garden,Garden Area (m2),Swimming Pool,Surface of the Land (m2),Number of Facades,Construction Year,PEB,Primary Energy Consumption (kWh/m2),State of the Building,Url
0,Ottignies-louvain-la-neuve,1348,House,exceptional-property,3790000,for-sale,6,750,0,0,...,0,0,1,160737,4,1961,E,359,To be done up,https://www.immoweb.be/en/classified/exception...
1,Anthee,5520,House,castle,550000,for-sale,2,200,1,0,...,0,0,0,110000,0,0,C,234,Good,https://www.immoweb.be/en/classified/castle/fo...
2,Dinant,5500,House,castle,550000,for-sale,2,200,1,0,...,0,0,0,110000,0,0,C,234,Good,https://www.immoweb.be/en/classified/castle/fo...
3,Namur,5000,House,castle,550000,for-sale,2,200,1,0,...,0,0,0,110000,0,0,C,234,Good,https://www.immoweb.be/en/classified/castle/fo...
4,Waasmunster,9250,House,castle,3000000,for-sale,6,967,0,0,...,0,0,1,101349,4,1810,F,708,Good,https://www.immoweb.be/en/classified/castle/fo...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10120,Leuven,3000,Apartment,kot,193000,for-sale,1,20,1,1,...,0,0,0,0,0,2017,A,0,As new,https://www.immoweb.be/en/classified/kot/for-s...
10121,Leuven,3000,Apartment,kot,195000,for-sale,1,18,1,1,...,0,0,0,0,0,2017,A,0,As new,https://www.immoweb.be/en/classified/kot/for-s...
10122,Blankenberge,8370,Apartment,apartment,549900,for-sale,3,225,0,0,...,0,0,0,0,0,2024,A,0,As new,https://www.immoweb.be/en/classified/apartment...
10124,Mechelen,2800,House,house,840860,for-sale,4,237,0,0,...,0,0,0,0,0,0,A,0,As new,https://www.immoweb.be/en/classified/house/for...
10125,Mechelen,2800,Apartment,apartment,289879,for-sale,1,69,0,0,...,0,0,0,0,0,0,A,0,As new,https://www.immoweb.be/en/classified/apartment...

In [ ]:
df.columns

Index(['Locality', 'Zip Code', 'Type of Property', 'Subtype of Property',
       'Price', 'Type of Sale', 'Number of Rooms', 'Livable Space (m2)',
       'Fully Equipped Kitchen', 'Furnished', 'Open Fire',
       'Number of Fireplaces', 'Terrace', 'Terrace Area (m2)', 'Garden',
       'Garden Area (m2)', 'Swimming Pool', 'Surface of the Land (m2)',
       'Number of Facades', 'Construction Year', 'PEB',
       'Primary Energy Consumption (kWh/m2)', 'State of the Building', 'Url'],
      dtype='object')

In [ ]:
# Replace 'Number of facades' with 1 where 'Type of Property' is 0 (apartment) and 'Number of facades' is 0
df.loc[(df['Type of Property'] == 0) & (df['Number of Facades'] == 0), 'Number of Facades'] = 1

# Replace 'Number of Facades' with 2 where 'Subtype of Property' is 'duplex' or 'town-house' and 'Number of Facades' is 0
df.loc[(df['Subtype of Property'].isin(['duplex', 'town-house'])) & (df['Number of Facades'] == 0), 'Number of Facades'] = 2

# Replace 'Number of Facades' with 4 where 'Type of Property' is 1 (House) and 'Number of Facades' is 0
df.loc[(df['Type of Property'] == 1) & (df['Number of Facades'] == 0), 'Number of Facades'] = 4

In [ ]:
df['Number of Facades'].isnull

0        False
1        False
2        False
3        False
4        False
         ...
10120    False
10121    False
10122    False
10124    False
10125    False
Name: Number of Facades, Length: 9988, dtype: bool

In [ ]:
df['Number of Facades'].value_counts()

Number of Facades
2    3279
4    3116
0    2291
3    1414
1      24
6       1
9       1
Name: count, dtype: int64

In [ ]:
df.to_csv('csv_files\\v1_dataset.csv', index=False)